# Generated by Django 5.0.3 on 2024-04-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Enter Your title", max_length=50)),
                (
                    "content",
                    models.CharField(
                        blank=True, default="enter your content", max_length=50
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, default=99.9999, max_digits=5
                    ),
                ),
            ],
        ),
    ]
