# Generated by Django 5.0.3 on 2024-04-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_content_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=4, default=0.0, max_digits=8, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                default=" Enter Your Title ", max_length=50, unique=True
            ),
        ),
    ]
